# This is a basic workflow to help you get started with Actions

name: gh-pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          path: node_modules
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Install Packages
        run: npm ci
        
      - run: npm run test
      
      - run: npm run build
        
      - name: Delpoy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
